#include "gq_xml.h"
#include <assert.h>
#include <stdlib.h>

int main(void) {
  const char *rss_xml =
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <rss version=\"2.0\" "
      "xmlns:atom=\"http://www.w3.org/2005/Atom\" > <channel> <xhtml:meta "
      "xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" name=\"robots\" "
      "content=\"noindex\" /> <title></title> <copyright><![CDATA[Copyright "
      "(C) 2025 Goodreads Inc. All rights reserved.]]> </copyright> "
      "<link>https://www.goodreads.com/</link> <atom:link "
      "href=\"https://www.goodreads.com/quotes/list_rss/"
      "12541417-james-fraser\" rel=\"self\" type=\"application/rss+xml\" /> "
      "<description><![CDATA[]]></description> <language>en-US</language> "
      "<lastBuildDate>Thu, 05 Sep 2013 18:30:22 -0700</lastBuildDate> "
      "<ttl>60</ttl> <image> <title></title> "
      "<link>https://www.goodreads.com/</link> <width>144</width> "
      "<height>41</height> "
      "<url>https://www.goodreads.com/images/layout/goodreads_logo_144.jpg</"
      "url> </image> <item> "
      "<guid>https://www.goodreads.com/quotes/"
      "30541-i-don-t-like-people-who-have-never-fallen-or-stumbled</guid> "
      "<pubDate>Thu, 05 Sep 2013 18:30:22 -0700</pubDate> <title> "
      "<![CDATA[James add a quote by Boris Pasternak]]> </title> <link> "
      "<![CDATA[https://www.goodreads.com/quotes/"
      "30541-i-don-t-like-people-who-have-never-fallen-or-stumbled]]> </link> "
      "<description> <![CDATA[\"I don't like people who have never fallen or "
      "stumbled. Their virtue is lifeless and it isn't of much value. Life "
      "hasn't revealed its beauty to them. \" -- Boris Pasternak]]> "
      "</description> </item> <item> "
      "<guid>https://www.goodreads.com/quotes/"
      "222643-seek-freedom-and-become-captive-of-your-desires-seek-discipline</"
      "guid> <pubDate>Mon, 15 Oct 2018 22:43:44 -0700</pubDate> <title> "
      "<![CDATA[James add a quote by Frank Herbert]]> </title> <link> "
      "<![CDATA[https://www.goodreads.com/quotes/"
      "222643-seek-freedom-and-become-captive-of-your-desires-seek-discipline]]"
      "> </link> <description> <![CDATA[\"Seek freedom and become captive of "
      "your desires.  Seek discipline and find your liberty.\" -- Frank "
      "Herbert]]> </description> </item> <item> "
      "<guid>https://www.goodreads.com/quotes/"
      "8235457-the-only-evidence-to-the-contrary-was-the-mute-protest</guid> "
      "<pubDate>Mon, 03 Dec 2018 21:59:43 -0800</pubDate> <title> "
      "<![CDATA[James add a quote by George Orwell]]> </title> <link> "
      "<![CDATA[https://www.goodreads.com/quotes/"
      "8235457-the-only-evidence-to-the-contrary-was-the-mute-protest]]> "
      "</link> <description> <![CDATA[\"The only evidence to the contrary was "
      "the mute protest in your own bones, the instinctive feeling that the "
      "conditions you lived in were intolerable and that at some other time "
      "they must have been different.\" -- George Orwell]]> </description> "
      "</item> <item> "
      "<guid>https://www.goodreads.com/quotes/"
      "53471-the-weariness-of-the-cell-is-the-vigour-of-the</guid> "
      "<pubDate>Thu, 06 Dec 2018 03:40:28 -0800</pubDate> <title> "
      "<![CDATA[James add a quote by George Orwell]]> </title> <link> "
      "<![CDATA[https://www.goodreads.com/quotes/"
      "53471-the-weariness-of-the-cell-is-the-vigour-of-the]]> </link> "
      "<description> <![CDATA[\"The weariness of the cell is the vigour of the "
      "organism.\" -- George Orwell]]> </description> </item> <item> "
      "<guid>https://www.goodreads.com/quotes/"
      "12825784-ambition-offends-eternal-truth-by-subordinating-truth-to-"
      "itself</guid> <pubDate>Fri, 09 May 2025 03:16:07 -0700</pubDate> "
      "<title> <![CDATA[James add a quote by Antonin Sertillanges]]> </title> "
      "<link> "
      "<![CDATA[https://www.goodreads.com/quotes/"
      "12825784-ambition-offends-eternal-truth-by-subordinating-truth-to-"
      "itself]]> </link> <description> <![CDATA[\"Ambition offends eternal "
      "truth by subordinating truth to itself.\" -- Antonin Sertillanges]]> "
      "</description> </item> </channel> </rss>";

  return EXIT_SUCCESS;
}
